title: Just Around the Corner
author: MLT
email: info@mtandev.com
description: > # this means to ignore newlines until "baseurl:"
  Everything you need to know about learning how to code is *just around the corner*.

# social links
twitter_username: @mich_linette
github_username:  mtandev

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
